name: Create a new release

on:
  push:
    branches: [ main ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      with:
        config-name: create-release-template.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}